# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b9e93881c8bd55fd2cd55f3739ad3f79512a5f60dc441cf400bcc1f23a30014c93456b3031f5d6f70155c388fb567d11f497407191696e848d782a27ef55f4a

test:
  secret_key_base: f5373b0dfdb5b1dcf0d1e766ceda4f8745fff5f7ec353f992988ddb78cb996c6dafcf4c766c59516f196006f090c55569805dff06e0fb1bed6feed2925fb6dc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
